### ISSUE TITLE
Readme install steps out of order

### ISSUE THREAD

**Issue by repertoire** [rufuspollock-okfn/textus#11]
cd src

should precede

npm install

Thanks!

**Comment by rufuspollock** [comment]
@repertoire can you submit a patch via a pull request?

**Comment by tomoinn** [comment]
Actually it needs a bit more love than that, I'm tidying up the configuration management and will update the readme to reflect the configuration for elaticsearch as well, at the moment even if you get it running without a data store it won't do much (currently just running elaticsearch on the same machine with the default settings will work though if you want to have a play)

**Comment by rufuspollock** [comment]
@tomoinn i assume you saw the config method used in Hypernotes (you probably have a better method!): https://github.com/okfn/hypernotes/commit/8c0bd87813d702892ae151a61a350cbfa90aacd6

**Comment by tomoinn** [comment]
Configuration now uses a mechanism similar (but not quite the same) to the one hypernotes uses, customised to work with Heroku
