### ISSUE TITLE
Import from openShakespeare 

### ISSUE THREAD

**Issue by tomoinn** [rufuspollock-okfn/textus#13]
Textus is in a state where we should be able to at least semi automagically import all the content from openshakespeare, especially as nick s has written some code recently to convert annotation locations specified as xpaths to character offsets as part of the work getting two different sets of annotations merged in openshakespeare itself. Given this was probably the only hard part there should be a small piece of glue code to write and everything should just work (hahahah, sorry, couldn't help myself...)

**Comment by JillyMathews** [comment]
Had a go with Nick. Not runnable by anyone who is not Nick. Can we ask Nick if he has the instructions.
