### ISSUE TITLE
System overview documentation

### ISSUE THREAD

**Issue by rufuspollock** [rufuspollock-okfn/textus#14]
Already have https://github.com/okfn/textus/blob/master/docs/architecture_overview.md but (I would suggest)  this needs extras thing like:
- Diagram showing general architecture - suggest the diagram is done in google drawings to easy to work on later ...
- API documentation - how does the RESTful API work
- Domain model overview

It's not perfect but the PyBossa docs give a sense of this: http://docs.pybossa.com/en/latest/index.html, see esp
- http://docs.pybossa.com/en/latest/overview.html
- http://docs.pybossa.com/en/latest/model.html

These docs are done in sphinx btw ...

**Comment by JillyMathews** [comment]
Will complete at the end of the project by September.
