### ISSUE TITLE
Documentation using Sphinx / Restructured Text

### ISSUE THREAD

**Issue by rufuspollock** [rufuspollock-okfn/textus#3]
Suggest we use sphinx / restructured text for the docs (http://sphinx.pocoo.org/):
- Sphinx / RST is much better for docs as you go forward than markdown (auto-built indexes, references etc etc)
- Can auto-build stuff with readthedocs ...

**Comment by tomoinn** [comment]
Looks neat, I'll move them over. Do we already have a readthedocs account of some kind of shall I just create one?

**Comment by rufuspollock** [comment]
Yes we already have a readthedocs account. Just notify here once you've converted over. Your probably want to use sphinx-quickstart (and move docs out the way while you do it).

**Comment by rufuspollock** [comment]
@tomoinn any update on this? cf #10 for partial duplicate + instructions ...

**Comment by tomoinn** [comment]
Slow on this one as all my Linux installs appear to be messed up and getting the sphinx tools working on win7 appears to be an exercise in applied frustration. I'll set up a proper box soon hopefully and get this fixed along with writing the extra docs which I suspect will come from the biblio hack sessions.
