### ISSUE TITLE
Only possible to be logged in on one browser

### ISSUE THREAD

**Issue by leighman** [rufuspollock-okfn/textus#50]
Running the git version on localhost I find that it is only possible to be logged in on one browser at a time.
I am using Google login so maybe a quirk of this.
If I log in on Opera then on Firefox, I am logged out when I go back to Opera. And vice versa.

**Comment by tomoinn** [comment]
In general you can't log in from multiple locations, whether that's two browsers or the same browser software on more than one machine. Is that actually a problem though? Changing it wouldn't be particularly difficult (see login.js in the server part of the code base) but I question whether it's actually important enough to do so.
