### ISSUE TITLE
New, more componentized architecture

### ISSUE THREAD

**Issue by rufuspollock** [rufuspollock-okfn/textus#59]
This [google drawing shows the technical architecture](https://docs.google.com/a/okfn.org/drawings/d/1S9Hv98LWdcfuG3KjF1qELsZBp-RQ08Ylo3gxaO6tyQg/edit)

<img src="https://docs.google.com/drawings/d/1S9Hv98LWdcfuG3KjF1qELsZBp-RQ08Ylo3gxaO6tyQg/pub?w=480&amp;h=360">

This [drawing shows the overview of how the web app could work](https://docs.google.com/drawings/d/1nIJl8EUfKEf8USDqXAgOH5mKv0PQ6kzocE9LvmEgiTQ/edit)

<img src="https://docs.google.com/drawings/d/1nIJl8EUfKEf8USDqXAgOH5mKv0PQ6kzocE9LvmEgiTQ/pub?w=480&amp;h=360">
## Components
- textus-viewer
- textus-formatter
## Core plan

Texts are processed into 2 components
- raw text
- syntax formatting (paragraphs, strong, em etc etc)
- NO annotation atm
### Wordpress

On wordpress page: /shakespeare/hamlet/

In the page we have shortcode:

<pre>
[textus:url]

url = url or raw text
url.typography.json = typography formatting
</pre>

Replace [textus:url] is replaced by

```
<div id=”raw”>
raw text
</div>
<script src=”textus-viewer.js”></script>
<script type=”text/javascript”>
var textusTypography = typography;
// now boot textus viewer
viewer = new Viewer(rawText, typography);
</script>
</pre>
```

**Comment by austgate** [comment]
The first version of the Wordpress back-end which stores and returns flat files is at https://github.com/austgate/textus_wp_middleware
