### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by emanuil-tolev** [rufuspollock-okfn/textus#60]
Hiya,

The http://textusproject.org/ website notes that this is an open-source project. I can't seem to (easily) find a COPYING or LICENSE or LICENCE file though. If there truly isn't one published within the repo, the default copyright rules would apply to this copy of the code and docs. These rules are pretty restrictive.

I'd have made a pull request, but obviously there has to be a decision wrt which license :).

As for why this might be important: a friend is AFAIK doing something with text annotations for a final year undergraduate dissertation computer science project, so I was going to suggest taking a look at TEXTUS. We're expected to have quite strong proof that we're not infringing any rights when using any code verbatim or modified.

**Comment by rufuspollock** [comment]
Excellent point. This was agreed to be MIT licensed but it seems there was a failure to add a license statement :-(

Pull requests welcome (we usually put the notice in the README e.g. [here](https://github.com/okfn/recline#copyright-and-license) but are happy with LICENSE.txt or similar!).

**Comment by emanuil-tolev** [comment]
"Copyright 2011-2013 Open Knowledge Foundation."

I take it. (earliest commit seems to be yours in Oct 2011, repo seems to be under Open Humanities working group)

Apologies for the bother, it's just - well, I can't do the copyright statement bit of MIT without those details.

**Comment by rufuspollock** [comment]
@emanuil-tolev - this is perfect, thank-you very much!. Could you submit a pull request on this repo and we'll get this merged.
