### ISSUE TITLE
Migrate textusproject.org content (blog esp) to here

### ISSUE THREAD

**Issue by rufuspollock** [rufuspollock-okfn/textus#64]

**Comment by todrobbins** [comment]
I can help!

**Comment by rufuspollock** [comment]
@todrobbins how are you doing here? Do you need any help to move forward with the migration (I think we have already confirmed on list what we need to move). I can also get you access to http://textusproject.com/ site (wordpress)

**Comment by todrobbins** [comment]
I'm close to a commit. I've migrate a few posts to the Jekyll format. Do we want a `_posts` directory in this repo? Or do we want to add the old posts to the OKFN Labs post history?

**Comment by todrobbins** [comment]
Here's a preview of what the blog posts are looking like:

![screen shot 2015-03-07 at 8 59 03 pm](https://cloud.githubusercontent.com/assets/158590/6544438/e09136ae-c50c-11e4-8c3f-684ff113944d.png)

**Comment by rufuspollock** [comment]
@todrobbins do you reckon this done in terms of migration? If so we can close and announce this successful effort to the list :-) Well done!

**Comment by todrobbins** [comment]
I just committed the last set of old blog posts. Closing this issue. Thanks!

**Comment by rufuspollock** [comment]
@todrobbins great work! Are you happy to email open-humanities list updating them on the excellent progress here.

My last action will be to request redirect from http://textusproject.com/ to http://okfnlabs.org/textus/

**Comment by todrobbins** [comment]
Sure. I'll send a message out in the next hour.
