### ISSUE TITLE
Style / theme the site

### ISSUE THREAD

**Issue by rufuspollock** [rufuspollock-okfn/textus#8]
Would be nice to have a proper theme / styling for the site. Suggest talking with @mintcanary ...

**Comment by rufuspollock** [comment]
Assigning to @samleon - may want to involve @mintcanary :-)

**Comment by rufuspollock** [comment]
Current styling at http://beta.openphilosophy.org/

Feel this probably needs a further iteration but already looks reasonable :-)

**Comment by tomoinn** [comment]
Yeah, I'm tending towards the 'redo with bootstrap' argument, having actually had a chance to sit down and look at it properly! Still, it'll do for now.

**Comment by rufuspollock** [comment]
Didn't realize you hadn't used bootstrap (definitely do!). Also have you chatted with @mintcanary?

**Comment by smth** [comment]
My feeling is that this should neutral enough to fit between the header and footer of the sites it may be implemented on. Here is my suggestion of how it could be tweaked: http://i.imgur.com/dSSKV.jpg

**Comment by tomoinn** [comment]
Pretty much implemented, enough for now certainly
